user.go
As defined in https://github.com/getlantern/engineering/issues/1916.  This is the API to be implemented by sub-tasks of that epic.  Much of this is adapted from the authentication client [already defined in lantern-client](https://github.com/getlantern/lantern-client/blob/aaa6d6a1147747658a6568d7dfce4f704cf7bb9c/internalsdk/auth/auth.go#L27-L49).  The idea is that we can port that code to implement most of this.  I changed the API a bit to:
- avoid leaking things like the salt through the abstraction (WIP; see comments below)
- manage some of the work for the caller, like storing the salt
=> Add user management API

radiance.go, radiance_test.go
- https://github.com/getlantern/engineering/issues/1920
- Implement `GetServers()` and remove `ActiveProxyLocation()` based on the request
=> #1920 Implement GetServers()

client/client.go, client/service/service.go, config/config.go, radiance.go, radiance_test.go
This passes the data directory to `boxservice` so it's not trying to write to the same log file as `slog`. It also passed it to `ConfigHandler` to save configs and calls `libbox.Setup`.
=> Pass data directory

radiance.go
This PR exposes `ConnectionStatus` method so the client can read the current connection status.
=> Expose connection to client.

app/app.go, backend/headers.go, go.mod, go.sum, issue/issue_test.go, radiance.go, radiance_test.go
The previous setup would use a generic directory under HOME for all platforms for both data and logs, but we want things like `~/Library/Logs/Lantern` on MacOS and `%AppData%` on Windows.
=> Use slightly different directories depending on platform and pass them to fronted

client/service/service.go
This PR resolves an issue where the app would crash or enter an invalid state on macOS if the VPN is started and stopped multiple times in a row: https://github.com/getlantern/engineering/issues/1994
It includes updates to properly reinitialize libbox after stopping and prevents multiple calls to libbox.Close() which caused the "file already closed" errors.
=> Fix app crash on macOS when starting/stopping VPN multiple times

go.mod, go.sum, option/amnezia.go, protocol/amnezia/endpoint.go, protocol/amnezia/outbound.go, protocol/register.go, transport/amnezia/client_bind.go, transport/amnezia/device.go, transport/amnezia/device_stack.go, transport/amnezia/device_stack_gonet.go, transport/amnezia/device_stack_stub.go, transport/amnezia/device_system.go, transport/amnezia/device_system_stack.go, transport/amnezia/endpoint.go, transport/amnezia/endpoint_options.go
closes https://github.com/getlantern/engineering/issues/2005
This PR brings AmneziaWG support by:
1. pointing to our version of wireguard-go (this doesn't change behavior of existing wireguard protocol)
2. creating a new 'amnezia' outbound protocol that supports the amnezia-specific config params
99.9% of the code is lifted from wireguard protocol implementation, except for the custom param passing
=> AmneziaWG as a separate protocol

client/service/service.go
This just updates the outbounds and endpoints when we receive a new config.
=> Actually update outbounds and endpoints

client/service/service.go, go.mod, go.sum
This pull request includes several updates to the `client/service/service.go` and `go.mod` files. The changes primarily focus on registering services, cleaning up context usage, and updating dependencies.
* [`client/service/service.go`](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9R87): Added a call to `service.MustRegister(ctx, lb.LogFactory())` in the `Start` method to ensure the service is registered with the provided log factory.
* [`client/service/service.go`](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9L219-R220): Removed outdated comments and ensured the log factory is retrieved from the context in the `updateOutboundsEndpoints` function.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca06116 …
=> retrieve box instance log factory, update sing-box-minimal

radiance.go
This pull request introduces several enhancements to the `Radiance` struct and related methods in the `radiance.go` file. The primary changes include adding an `httpClient` field to the `Radiance` struct, initializing it in the `NewRadiance` function, and adding new methods to expose the `httpClient` and retrieve the user object.
Key changes:
* Added `httpClient` field to the `Radiance` struct to manage HTTP client configurations.
* Initialized the `httpClient` field in the `NewRadiance` function using `k.NewHTTPClient()`.
* Added `User` method to the `Radiance` struct to return the user object associated with the client.
* Added `HttpClient` method to the `Radiance` struct to expose the HTTP client used by the Radiance client.
=> Expose multiple methods

client/service/service.go
This pull request includes a minor update to the `client/service/service.go` file. The change modifies the context parameter passed to the `Start` method of `mutRuleSetManager`.
* [`client/service/service.go`](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9L91-R91): Updated the context parameter from `bs.ctx` to `ctx` in the `Start` method call for `mutRuleSetManager`.
=> pass ctx to ruleset manager

client/client.go
This pull request updates the `vpnClient` implementation in `client/client.go` to improve the handling of VPN connection status. The primary changes involve setting the connection status during the start and stop of the VPN and simplifying the `setConnectionStatus` method.
* [`client/client.go`](diffhunk://#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09R118): Updated `StartVPN` to call `setConnectionStatus(true)` when the VPN starts, ensuring the connection status is accurately reflected.
* [`client/client.go`](diffhunk://#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09R141): Updated `StopVPN` to call `setConnectionStatus(false)` when the VPN stops, maintaining consistency in connection status tracking.
* …
=> Fix connection status state

config/fetcher.go, radiance.go, radiance_test.go
This honors the log directory passed into options on radiance creation and uses the new config endpoint.
=> Fix directory handling when radiance is created

backend/headers.go, config/fetcher.go, config/fetcher_test.go, go.mod, go.sum, issue/issue.go
This pull request refactors the handling of user-related headers and configuration data in HTTP requests by removing the dependency on the `user.BaseUser` type across multiple functions. It simplifies the codebase by consolidating header logic and reducing parameter dependencies. Additionally, it updates the `go.mod` file to use a newer version of the `github.com/getlantern/common` library.
* Removed the `user.BaseUser` parameter from `NewRequestWithHeaders` and `NewIssueRequest` functions in `backend/headers.go`. User-related headers such as `userIDHeader` and `deviceIDHeader` were removed, and a simplified `User-Agent` header was added instead. (`[backend/headers.goL31-R42](diffhunk://#diff-e07fb405996bcf124cc1c767f6851c1f8ff05caee363cdd6de36cfb9ab43c574L31-R42)`)
* Updated the …
=> Use new config request format

client/client.go, config/config.go, config/config_test.go, config/fetcher.go, config/fetcher_test.go, go.mod, go.sum, radiance.go, user/user.go
The locale is used in user creation on first run, so we need to pass it.
This pull request introduces support for locale detection and propagation throughout the application, along with minor updates to dependencies and error messaging. The most significant changes involve adding locale support to configuration handling and ensuring the locale is detected and passed through various components.
* Added a `Locale` field to the `Options` struct in `client/client.go` to store the user's locale.
* Updated `NewConfigHandler` in `config/config.go` to accept a `locale` parameter and propagate it to the `fetcher` for configuration fetching. [[1]](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L69-R69) [[2]](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d0 …
=> Pass locale in config requests

api/api.go, client/service/service.go, init.go, init_test.go, issue/issue.go, radiance.go, radiance_test.go
**Problem:**
Upon app startup, we need to make several API calls. However, due to the separation of the Radiance processes, these calls cannot be made on iOS, as Radiance runs in a completely isolated process.
**Solution (for now):**
I have exposed a new `NewAPIHandler` that provides access to all the required APIs, which can be invoked without Radiance set up. To minimize duplication, I've tried to reuse as much code as possible, given that on other platforms, we can run in the same process and avoid the isolation issues.
I'm open to suggestions for a better solution.
**Copilot Summary**
This pull request refactors the `Radiance` initialization process to improve code modularity and reusability. It introduces a shared configuration structure (`sharedConfig`) and a new `APIHandler` type, …
=> IOS cleanup

client/client.go, client/service/service.go, radiance.go, radiance_test.go
This pull request refactors configuration parsing and introduces a shared base context for the `BoxService`. The most significant changes include removing the `ParseConfig` method from the `VPNClient` interface and `vpnClient` implementation, creating a global `BaseContext` function for shared context management, and updating the configuration handler to use the new `ParseConfig` function in `BoxService`.
* Removed the `ParseConfig` method from the `VPNClient` interface and its implementation in `vpnClient`, delegating the responsibility to `BoxService`. (`client/client.go`, [[1]](diffhunk://#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09L51) [[2]](diffhunk://#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09L220-L223)
* Added a new `ParseConfig` …
=> create base sing-box ctx

client/service/service.go, client/service/service_test.go, radiance_test.go
This pull request introduces enhancements to the `BoxService` configuration handling, adds new unit tests for improved test coverage, and includes minor improvements in resource management for existing tests. Below is a summary of the most important changes:
* Refactored the `OnNewConfig` method in `BoxService` to serialize configuration options into JSON, store them as a string, and ensure thread-safe handling when the service is not running. This improves maintainability and ensures proper locking.
* Added `TestOnNewConfig` in `service_test.go` to verify the behavior of the `OnNewConfig` method, including scenarios where the service updates the configuration successfully or does nothing when not running.
* Added `defer r.Close()` in `TestNewRadiance` and `TestReportIssue` to ensure …
=> Actually fix crash

client/client.go
This PR just initializes the ruleset for the custom server manager.
* Added support for a "custom server selector" by introducing a new ruleset handler (`customServerSelector`) in the `NewVPNClient` function. This is initialized similarly to the existing split tunnel handler, with a placeholder for persisting user preferences.
* Updated the routing rules in `NewVPNClient` to include the custom server selector's rule and ruleset, ensuring it integrates seamlessly with the existing split tunnel functionality.
* Renamed `initTunnel` to `initMutRuleSet` to better reflect its purpose of initializing mutable ruleset handlers. This change improves code readability and aligns with the terminology used in the project.
* Standardized the naming of constants for the custom server feature, changing …
=> initialize custom server selector ruleset

config/config.go, config/config_test.go, go.mod, go.sum
This switches back to using mergo for merging config structs so that we preserve the elements of the old config we want while using elements of the new config we want. This allows the server side to carefully include only the changes we desire vs responding the the entire sing-box options every time.
This pull request refactors the configuration merging logic in `config/config.go` to improve maintainability and correctness. It replaces the custom `mergeResp` function with the `mergo` library for merging configurations and updates the associated test suite to ensure comprehensive coverage of the new behavior.
* Replaced the custom `mergeResp` function with an implementation using the `mergo` library to simplify and improve the merging logic for configuration responses. The new …
=> Updated config merge to preserve elements we want to from old config while using new elements we want

client/service/service.go, config/config.go, config/config_test.go, go.mod, go.sum, radiance.go
Copilot couldn't actually describe what this PR does.
This PR changes the config parser/unmarshaller to parse as a `ConfigResponse` object, instead of a `Config` object. This fixes a bug where the box options were being overwritten with an empty one on every fetch.
* Added new `Options` struct in `ConfigHandler`, encapsulating all configuration options passed to `NewConfigHandler`. (`config/config.go`, [[1]](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L50-R61) [[2]](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L74-R103)
* Added a `mergeResp` function to handle deep merging of old and new configuration responses, ensuring proper updates while preserving specific fields. (`config/config.go`, …
=> fix unmarshal bug. unmarshal as configresponse instead of config.Config

client/boxoptions/options.go, client/service/custom_server_manager.go, client/service/service.go, client/service/service_test.go
This pull request refactors the configuration handling in the `BoxService` to use structured `option.Options` instead of raw strings, introduces default base outbounds and endpoints, and updates the options with the new outbounds and endpoints from recent config.
* Updated `BoxService` to use `option.Options` for configuration instead of raw strings. This includes changes to the `New`, `Start`, and `OnNewConfig` methods, as well as the `newLibboxService` function. (`client/service/service.go`: [[1]](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9L61-R79) [[2]](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9L95-R101) [[3]](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9L141-R156) …
=> update box options on new config

client/boxoptions/options.go, client/client.go, client/service/service.go, config/config.go
This pull request introduces logging enhancements, temporary configuration adjustments, and minor refactoring to improve code maintainability and debugging capabilities. 
* Added error logging in `StartVPN` to capture failures when starting the `boxService` (`client/client.go`).
* Introduced debug logs in `updateOutbounds` and `updateEndpoints` to provide more visibility into the creation of outbounds and endpoints (`client/service/service.go`) [[1]](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9R359) [[2]](diffhunk://#diff-3e93cc11b22eab442b7c9435196e3101e2ac6f286ee1b63c98f0de4099bc5ab9R397).
* Added debug logging for `libbox` service creation, including serialized options for better traceability (`client/service/service.go`).
* Limited the `Endpoints` …
=> Temp wg patch

client/boxoptions/options.go, client/service/service.go
This pull request introduces significant changes to the `boxoptions` and `service` packages, primarily focused on refactoring the outbound configuration to use a new `LanternURLTest` tag and adding functionality to dynamically manage URLTest outbounds. The changes improve modularity and flexibility in handling outbound configurations.
* Introduced a new constant `LanternURLTestTag` and a helper function `URLTestOutbound` to define URLTest outbounds, improving clarity and reusability in outbound setup (`client/boxoptions/options.go`). [[1]](diffhunk://#diff-376a60d662a43ac127f3219f7d86b8fcd9d1d1371dbcd9fe37d91a99195f857bR6-R15) [[2]](diffhunk://#diff-376a60d662a43ac127f3219f7d86b8fcd9d1d1371dbcd9fe37d91a99195f857bR142-R157)
* Added logic in `OnNewConfig` to dynamically update the …
=> add lantern urltest outbound

api/pro.go, api/pro_api.go, api/user.go, api/user_api.go, api/user_test.go, init.go, radiance.go
This pull request introduces new functionality for user data retrieval and OAuth login, along with associated tests and minor refactoring. The most important changes include adding a `UserData` method to retrieve user data, implementing an `OAuthLoginUrl` method for initiating OAuth login, and updating tests to cover the new functionality.
* Added a `UserData` method to the `Pro` struct and `ProClient` interface to fetch user data from the API, log errors, and save the retrieved data to the user configuration. (`api/pro.go` [[1]](diffhunk://#diff-e4dc6bb43b725d271e3a42224c03ccbbfa8027d8f30a9b71047791bdfaacc58eR57-R66) `api/pro_api.go` [[2]](diffhunk://#diff-117fab96fad71f627d01ee7eb717de3ebce047a86dc8f275c28e3ee62547fedcR26) [[3]](diffhunk://#diff-117fab96fad71f627d01ee7eb717de3ebce047a86d …
=> OAuth APIS

go.mod, go.sum
This includes a fix where we use platforminterface whenever it's not nil. This also fixes a broken build with sing-box-extensions diverging from sing-box.
=> latest sing-box-minimal

common/platform.go, vpn/vpn.go
This pull request introduces changes to improve the initialization and logging process in the `vpn/vpn.go` file. The most significant updates include adding support for passing configuration options via the `radiance.Options` struct, ensuring proper initialization of shared resources, and enhancing logging for debugging purposes.
* Updated the `QuickConnect` and `ConnectToServer` functions to accept a new `radiance.Options` parameter, ensuring that paths and logger configurations are properly initialized using `common.Init`. This prevents potential issues with uninitialized resources. [[1]](diffhunk://#diff-25828e7146300d37842032752af02678c7c569a51995a9d0314e1ec400cdb94eR21-R42) [[2]](diffhunk://#diff-25828e7146300d37842032752af02678c7c569a51995a9d0314e1ec400cdb94eL51-R69)
* Added a …
=> Add options parameter to VPN connect functions

config/config.go, config/fetcher.go, vpn/boxoptions.go, vpn/tunnel.go, vpn/vpn.go
This pull request refactors and improves the handling of "auto" server selection and status reporting in the VPN tunnel logic. The changes clarify the logic for auto-selection, ensure correct placeholder behavior, and improve status reporting for selected and active servers.
**Auto server selection and outbound management:**
* Refactored the logic for creating and updating the "auto-all" outbound group, ensuring it correctly switches between a placeholder and a real outbound based on the availability of lantern and user servers. Added the `updateAuto` function to encapsulate this logic.
* Changed the handling of tags for auto outbounds in `buildOptions` and `updateServers`, removing legacy code and ensuring that only relevant tags are included in the "auto-all" outbound. …
=> Fix active server

vpn/boxoptions.go, vpn/vpn.go
Use `autoAllTag` consistently when handling the "all" group in `QuickConnect`. Add a "catch-all" reject routing rule to prevent fallthrough.
=> Fix auto select on first connect

fronted.go, radiance.go
This pull request refactors the `radiance` package by moving the `newFronted` function and its supporting types from `radiance.go` into a new file, `fronted.go`. It also introduces a new method for retrieving server locations from the configuration. The changes improve code organization and add new functionality.
**Refactoring and Code Organization:**
* Extracted the `newFronted` function, the `lazyDialingRoundTripper` type, and the `slogWriter` type from `radiance.go` into a new file, `fronted.go`, to improve code modularity and maintainability. [[1]](diffhunk://#diff-4c0bae8138ac14baaa1ae94e99e7cd771ca5a489668864545f5e95e2707c4491R1-R104) [[2]](diffhunk://#diff-60179a9bacb28016fc7cda79abcad6f09a5c467689999b56f2c6e0cb3d94140cL255-R267)
**New Functionality:**
* Added a new method …
=> Expose server locations

vpn/ipc/clash_mode.go, vpn/ipc/outbound.go, vpn/vpn.go
This pull request adds enhanced logging throughout the VPN IPC and control flow to improve observability and debugging. The most significant changes include introducing structured logging at various points in the server and VPN logic, and standardizing log levels using a custom internal logging level system.
**Logging improvements:**
* Added structured logging using `slog` at key points in `clash_mode.go` and `outbound.go`, including when setting clash mode, selecting and setting outbounds, and when changing clash mode, with appropriate log levels for trace and debug messages. [[1]](diffhunk://#diff-3ce324cc266d1c23e1cdd6410073379caa2478bdf4bf7696663584c1bde17d41R6-R12) [[2]](diffhunk://#diff-3ce324cc266d1c23e1cdd6410073379caa2478bdf4bf7696663584c1bde17d41R58) …
=> add logging to server select function and related ipc handlers

README.md
This pull request updates the documentation for environment variable configuration in `README.md` to clarify where `.env` files can be placed and adds a new environment variable for log output control.
Documentation improvements:
* Clarified that configuration can be controlled by setting environment variables or creating a `.env` file in the same directory as the compiled executable or project root directory, rather than only in the project root.
* Updated the list of available environment variables to include `RADIANCE_DISABLE_STDOUT_LOG`, which disables printing `radiance` logs to STDOUT while still writing logs to the log file.
=> feat(docs): update env variable instructions

vpn/vpn.go
This pull request adds additional trace-level logging to the `AutoServerSelections` function in `vpn/vpn.go`. These logs will help with debugging by providing more visibility into the group retrieval and selection logic.
Logging improvements:
* Added a trace-level log statement after retrieving groups to display the fetched groups.
* Added a trace-level log statement when a group is not found or has no selection, including the relevant tag information.
=> add trace logs to AutoServerSelection
